### PR TITLE
full reconnect to nats #49

### LINKED ISSUE #49: Full reconnect to nats streaming.
Command line options:
- time between reconnects
- amount of attempts/infinite attempts/no attempts

Implementation:
- on connection losing destroy socket, and create a new socket
- if fail to connect, sleep and try again
- on success connect, reset attempts counter to zero
- on startup on fail to connect don't do attempts to connect

### PR DESCRIPTION
**Pull request by soft-bagel-93**

### CODE REVIEW

**Review by afalaleev — CHANGES_REQUESTED** [review]
The code has become confusing.
More than one time:
- connecting to the unix socket
- initializing of signal handlers
- searching of commit block
- reading of message backup 
- etc ...

There are only two places where connection can be lost:
- https://github.com/cyberway/cyberway.notifier/blob/0c0ae7bd79d1db11dbe08caeaf6fa968fa21f628/notifier.cpp#L129
- https://github.com/cyberway/cyberway.notifier/blob/0c0ae7bd79d1db11dbe08caeaf6fa968fa21f628/notifier.cpp#L108
- 
https://github.com/cyberway/cyberway.notifier/blob/0c0ae7bd79d1db11dbe08caeaf6fa968fa21f628/notifier.cpp#L116

You should investigate which place is better.
I think this place https://github.com/cyberway/cyberway.notifier/blob/0c0ae7bd79d1db11dbe08caeaf6fa968fa21f628/notifier.cpp#L116 is enough to reconnect.

**Review by afalaleev — COMMENTED** [review]
Do you check that these changes work?
According to the source code, this is not so.

**Comment by afalaleev** [comment]
Reconnect happens in this place, and this is a crutch :
https://github.com/cyberway/cyberway.notifier/pull/51/files#diff-072286657057991baaeb77690ee633a4L130

Your change with function `processing()` and `working` looks redundant,

Is it possible to make changes more simple?
Can we make reconnect in `_nats_connection_lost_cb` ?
Can you investigate documentation and examples in nats library ?

**Review by afalaleev — CHANGES_REQUESTED** [review]
There is still exists the big loop with 24000 attempts to send packet.
https://github.com/cyberway/cyberway.notifier/blob/2d1c3cceb80b9c51b1533450370091ebe0157b7a/notifier.cpp#L122

File: notifier.cpp [hunk 1]
```diff
@@ -118,25 +118,15 @@ static void _nats_connection_lost_cb(stanConnection*, const char* errTxt, void*)
...
-            continue;
-        }
-        break;
+    if (async) {
+        s = stanConnection_PublishAsync(sc, msg.subject.c_str(), msg.data.c_str(), msg.data.size(), _nats_publish_ack_cb, (void*)msg.index);
+    } else {
+        s = stanConnection_Publish(sc, msg.subject.c_str(), msg.data.c_str(), msg.data.size());
     }
 
+    if (s == NATS_CONNECTION_CLOSED) {
```
Comment (afalaleev) [inline notifier.cpp]: What is this if-case for?

File: notifier.cpp [hunk 2]
```diff
@@ -266,6 +256,15 @@ int main(int argc, char** argv) {
     if (s == NATS_OK) {
         s = stanConnOptions_SetConnectionLostHandler(connOpts, _nats_connection_lost_cb, nullptr);
     }
+    if (s == NATS_OK) {
+        s = natsOptions_SetMaxReconnect(opts, maxAttempts);
+    }
+    if (s == NATS_OK) {
+        s = natsOptions_SetReconnectWait(opts, interval);
+    }
```
Comment (afalaleev) [inline notifier.cpp:260]: natsOptions_SetReconnectBufSize should be added too

**Review by afalaleev — CHANGES_REQUESTED** [review]

File: options.h [hunk 3]
```diff
@@ -45,6 +45,11 @@ bool        deliverLast = true;
 uint64_t    deliverSeq  = 0;
 bool        unsubscribe = false;
 
+uint64_t    interval         = 10000; // 10 seconds
+uint64_t    maxAttempts      = 1;
+uint64_t    reconnectBufSize = 1024; // 1 MB
```
Comment (afalaleev) [inline options.h]: By default, the buffer size is 8Mb:
http://nats-io.github.io/nats.c/group__opts_group.html#gaa0d4b7ece8477cb9879f0dafff3456a5

But it can be very small for our usage, so set default buffer size to 8Mb and allow to change size to big values via options.

File: options.h [hunk 4]
```diff
@@ -108,6 +113,8 @@ static void printUsageAndExit(const char* progName, const char* usage) {
         "-tlsciphers    ciphers suite\n"
         "-tlshost       server certificate's expected hostname\n"
         "-tlsskip       skip server certificate verification\n"
+        "-interval      interval between reconnection attempts (in ms, default is 10000)\n"
+        "-attempts      number of reconnection attempts (-1 is infinity, default is 1)\n"
```
Comment (afalaleev) [inline options.h:117]: Add the option to change the reconnect buffer size.

**Review by afalaleev — CHANGES_REQUESTED** [review]

**Review by afalaleev — APPROVED** [review]
